### ISSUE TITLE
issue with filters

### ISSUE THREAD

**Issue by nog31** [apoutchika/MediaBundle#1]
Hello,

I have to say it, that bundle is fabulous !

I have some trouble with filters, in my formType I do this :

```
    $entity = $builder->getData();

    $builder
        ->add('name')
        ->add('logo', 'apoutchika_media_one', array(
            'filter' => 'entity:'.$entity->getId()
        ))
        ->add('medias', 'apoutchika_media_many', array(
            'filter' => 'entity:'.$entity->getId()
        ))
    ;
```

And it returns me : filter not correct; whatever I put.

Another issue when I add :

'contexts' => 'image',

returns "The context image is not defined."

**Comment by nog31** [comment]
La requete doit avoir un paramètre "filter" correct.

**Comment by nog31** [comment]
I had to configure it in app/config/config.yml so it's ok for contexts.

But not ok at all for filters, can anyone help me, please?

**Comment by nog31** [comment]
Another point : how to render an image with 100% size?

**Comment by apoutchika** [comment]
Hi,
Thank you for your interest in this bundle ;-)

Yes, you have see a bug in the filter, i have fixed this and pushed new version, use the 0.1.7 and say me if it's ok for you!

**Comment by apoutchika** [comment]
For render with 100% size, use :
{{ media|media_html }}
{{ media|media_url }}

See on https://github.com/apoutchika/MediaBundle/blob/master/Resources/doc/rendermedia.md

-> If you has set limit in config, the 100% size is this limit. Remove this config if you don't want resize it after upload

**Comment by nog31** [comment]
Thank you very much, it is working perfectly now! 

I have some responsive blocks on the front-end and have to add some class on the picture I render so it can adapt to the size of the block;

It can be useful to have the 100% choice, on the twig rendering ;)

Thank you again, I probably add your bundle to all my projects;

**Comment by apoutchika** [comment]
If the issue is on front, use the media_url filter and custom you'r image with css

html file

``` html
<img src="{{ media|media_url }}" class="img-responsive" />
```

css file

``` css
.img-responsive {
    width: 100%;
}
```

ps: If you like this bundle, share it ;-)

**Comment by nog31** [comment]
Thank you for your support I am going to share it for sure!
