### ISSUE TITLE
La requete doit avoir le paramètre "filter".

### ISSUE THREAD

**Issue by nog31** [apoutchika/MediaBundle#2]
Bonjour,

J'ai cette erreur lors de l'upload de fichiers vidéo supérieurs à 10Mo, pour des fichiers 1 à 2 Mo tout fonctionne bien !

Est-il possible d'ordonner les fichiers et leur donner une priorité pour retrouver cet ordre lors de l'affichage?

**Comment by apoutchika** [comment]
Bonjour,

Tu as probablement laissé la configuration de php post_max_size à 8M.

**Comment by nog31** [comment]
Bonjour,

J'ai bien vérifié toutes les réglages relatifs à la taille des requêtes sur le serveur et tout est OK;
- que ce soit sur nginx, php ou fpm...pour les parametres post, upload...

L'erreur que je reçois est bien :
La requete doit avoir le paramètre "filter".

Le plus bizarre : tout marche très bien lors d'uploads depuis une connexion fibre!
Est-ce que celà pourrait être dû à la lenteur de la connexion? un parametre qui se perd en route?

Je cherche toujours un moyen de trier les images lors de l'affichage : est-il possible de définir une priorité?

**Comment by nog31** [comment]
je vais utiliser la balise titre ou description pour faire mon tri...

A quoi correspond cette erreur?

La requete doit avoir le paramètre "filter".

Merci pour vos retours,

**Comment by apoutchika** [comment]
Le paramètre 'filter' correspond au filtre du formulaire (ex: user:42). Celui-ci est en sha1 et doit être envoyé en même temps que le média (même si il n'est pas défini).

Peux-tu regarder ce qui est envoyé en ajax via ton formulaire, et ce que tu reçois dans la méthode getFilter au niveau du post https://github.com/apoutchika/MediaBundle/blob/master/Controller/MediaRestController.php#L323

**Comment by apoutchika** [comment]
Hello,

Ce bug est fixé dans la version 0.1.10
