### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by nog31** [apoutchika/MediaBundle#3]
Hello,

I am using your bundle since a lot now and I love it !

I tried to had alias but it seems not working;

First I change the config.yml like this : 

`alias:
        thumbnail: { width: 100, height: 100, focus: true }`

Then I tried to upload photos and I am still having 3 folders : 
- original
- 500*400 (no way to remove)
- 78*44_focus (no way to remove)

Have you any idea of what I am doing wrong?

Thank you for your support,

**Comment by apoutchika** [comment]
Hello,

Thank for using my bundle !

When you send a new file, it's saved  only on "original" directory. When you use alias, (ex: your 'thumbnail'), the media is cropped only when you try to show or get it.

For use your alias in twig, try this : 

``` twig
{{ entity.media|media_html('thumbnail') }}
```

Only when you call this template, the new directory (100x100_focus) is created. See on [alias documentation](https://github.com/apoutchika/MediaBundle/blob/master/Resources/doc/rendermedia.md#use-alias-)

It works for you ?

**Comment by nog31** [comment]
Thank you for your answer !

It is now working perfectly on the front-office but I use media-bundle via custom API and I need to generate thumbnails on upload, is there a way to generate it via code?

**Comment by apoutchika** [comment]
The thumbnails are not generated when upload.

But, you can generate thumbnails with php on your API, add the 2nd parameter of getX : 

``` php
<?php
$mediaManager = $this->get('apoutchika_media.manager.media');

$url = $mediaManager->getUrl($media, 'thumbnail');
// or
$absoluteUrl = $mediaManager->getAbsoluteUrl($media, 'thumbnail');
// or
$path = $mediaManager->getPath($media 'thumbnail');
```

It work same front-office, with alias or size ('100x100_focus').

**Comment by nog31** [comment]
Thank you very much !!!

It's perfect ^^
