### ISSUE TITLE
Symfony 3.1

### ISSUE THREAD

**Issue by afiocre** [apoutchika/MediaBundle#4]
Hi,

is it possible to change the composer.json requirement in order to use with Symfony 3.1 (if compatible) ?

Thanks

**Comment by apoutchika** [comment]
Hi,

I finish to migrate this bundle to symfony 3.x. on tag 3.0.2

For install and use it, follow the documentation : https://github.com/apoutchika/MediaBundle/blob/master/Resources/doc/install.md

Good week
